-- ============================================================
-- Import Tồn đầu tháng 5/2026 từ dữ liệu tổng kết tháng 4/2026
-- Nguồn: TỒN CUỐI tháng 4 = Tồn đầu tháng 5
-- Giá trị âm đã được đặt về 0
-- Ngày tạo: 2026-05-26
-- Chạy trong: Supabase Dashboard → SQL Editor
-- ============================================================

BEGIN;

-- Bảng tạm chứa dữ liệu import
CREATE TEMP TABLE tmp_ton_dau_t5 (
  ten_san_pham TEXT,
  ton_cuoi     NUMERIC
);

INSERT INTO tmp_ton_dau_t5 (ten_san_pham, ton_cuoi) VALUES
  ('Băng dính hàng dễ vỡ', 121),
  ('Băng dính trong cuộn to', 2),
  ('Băng dính trong nhỏ 2cm', 10),
  ('Bánh oreo', 100),
  ('Bánh quế que socola', 0),
  ('Bắp ngô ngọt', 0),
  ('Baroi xông khói', 0),
  ('Bát giấy nâu size 8 làm maccaron', 5),
  ('Bát giấy trắng size 10 làm bánh bao', 21),
  ('Bi đường bạc', 1),
  ('Bì lợn', 0),
  ('Bìa 35x45', 39),
  ('Biển báo nhỏ -PK', 0),
  ('Biển báo to -PK', 0),
  ('Bộ dao đĩa', 750),
  ('Bơ hạt phỉ golden farm', 1),
  ('Bơ hokkaido Vivo (10 kg/kiện)', 5),
  ('Bơ matcha', 2),
  ('Bộ máy xúc -PK', 0),
  ('Bơ New Anchor 4x5kg', 46.3),
  ('Bơ ngọt dạng miếng (10 túi / thùng)', 5),
  ('Bơ quả cấp đông', 9),
  ('Bơ sữa Lactic 25kg HN', 25),
  ('Bò xay', 0),
  ('Bóng chùm-PK', 0),
  ('Bột baking soda', 2),
  ('Bột bánh mì ngũ cốc (Kraftkorn mix export)', 4),
  ('Bột bắp (25kg)', 25),
  ('Bột béo Kota', 1),
  ('Bột biến tính', 16),
  ('Bột bông hồng 25kg', 225),
  ('Bột cà ri', 1),
  ('Bột cacao túi 1kg', 18),
  ('Bột chanh 400g/túi', 2),
  ('Bột chiên xù gói 1kg', 2),
  ('Bột chocolate ONE', 2),
  ('Bột con voi', 0),
  ('Bột khoai tím (túi 500g)', 5),
  ('Bột Kim Sơn', 1),
  ('Bột làm bizonzon Thanh Hóa', 25),
  ('Bột mì đen', 5),
  ('Bột mì Semola Divella 2kg (bột áo pizza)', 5),
  ('Bột mochi túi 1kg', 0),
  ('Bột mỳ 999 (bao 25kg)', 16),
  ('Bột mỳ Hàn Quốc Cona 1kg', 34),
  ('Bột mỳ nguyên cám Bods red mill 2,27kg/túi', 5),
  ('Bột năng túi 1kg', 10),
  ('Bột nấu chè 1kg', 8),
  ('Bột nếp Thái 1kg bizonzon', 17),
  ('Bột nổi làm bánh AB mauri', 4),
  ('Bột nổi UCC Bico hộp 1kg', 2),
  ('Bột oreo', 4),
  ('Bột rau câu Sóc Vàng', 18),
  ('Bột rong câu giòn - Agar', 28),
  ('Bột Semola Semolina dạng thô Divella', 10),
  ('Bột su kem cremyvit 5kg/túi', 2),
  ('Bột sư tử 1kg/túi', 4),
  ('Bột sữa Almer 941 túi 900g', 35),
  ('Bột sữa khoai môn', 2),
  ('Bột sương sáo 50g/túi', 3),
  ('Bột tỏi', 4),
  ('Bột trà xanh matcha ĐL 500g', 15),
  ('Bột trà xanh Uji Ceremonial 50g', 2),
  ('Bột trộn bánh mỳ Lúa Mạch Đen 5Kg', 0),
  ('Bột trộn bánh mỳ nguyên cám  Puravita 5kg', 5),
  ('Bột trộn sẵn bánh ẩm sô-cô-la túi 5kg', 11),
  ('Bột trộn sẵn bánh redvelvet túi 5kg', 6),
  ('Bột vỏ bánh Taiyaki Nhật Bản túi 1kg', 19),
  ('Bột xe đạp xanh / blue2 (25kg)', 200),
  ('Bút bi', 24),
  ('Bút lông đen bé', 1),
  ('Cà chua', 0),
  ('Cà Paste La Sicilia 3kg', 0),
  ('Cà phê phố đen', 2),
  ('Cà rốt', 0),
  ('Cam vàng TQ', 0.002),
  ('Cây dừa PK', 0),
  ('Chai đựng thạch dừa PET 500ml cổ 42 (dây 95c)', 1),
  ('Chai sữa chua uống (dây 240c)', 240),
  ('Chân gà sả ớt tiến vua Sevifood túi 850g', 7),
  ('Chanh leo tươi', 0),
  ('Chanh tươi', 2),
  ('Chất ổn định bico không màu (20kg)', 2),
  ('Chuối quả', 0),
  ('Cinamoro-PK', 0),
  ('Cốc cupcake size to', 2),
  ('Cốc đựng set 4/6', 330),
  ('Cốc tim làm set 4/6', 0),
  ('Cơm dừa', 6),
  ('Cốm hạt nhiều màu', 0),
  ('Cốm tươi (khau phạ)', 4),
  ('Cồn 70 độ', 3),
  ('Cream cheese 1.36Kg', 35),
  ('Cream cheese Dairymont 2Kg', 7),
  ('Creamy (12 hộp)', 36),
  ('Củ hành khô', 0),
  ('Củ tỏi', 0),
  ('Cùi bưởi 1kg', 16),
  ('Cúp bóng đá-PK', 0),
  ('Đá viên', 8),
  ('Dăm bông', 0),
  ('Dấm trắng 500ml', 25),
  ('Đậu đỏ 3kg', 6),
  ('Dầu hào', 7),
  ('Dầu hướng dương loại 1L', 135),
  ('Dầu oliu can 5l', 2),
  ('Dầu tê', 2),
  ('Dâu tươi', 0),
  ('Dây thừng', 0),
  ('Đế ép chữ nhật 30x40cm', 50),
  ('Đế ép vuông 40x40', 20),
  ('Đế ngọc 26cm', 300),
  ('Đế ngọc 30cm', 0),
  ('Đế ngọc 32cm', 52),
  ('Đế trắng size 30', 0),
  ('Đế tròn bạc size 35 bánh 2 tầng', 10),
  ('Dĩa lẻ', 3),
  ('Dưa chuột', 0),
  ('Dừa sợi', 0),
  ('Đường ăn kiêng', 3),
  ('Đường đen nữ hoàng Biên Hòa', 11),
  ('Đường nâu', 3),
  ('Đường phèn bao 10kg', 0),
  ('Đường thốt nốt túi 1kg', 38),
  ('Đường thốt nốt túi 2,5kg', 0),
  ('Đường trắng 50kg/bao', 450),
  ('Đường xay (túi 1kg)', 6),
  ('Elsa PK', 0),
  ('Em bé múa bale tóc hồng cánh nhỏ', 0),
  ('Falu Dâu can 2 lít', 2),
  ('Falu mật ong can 2 lít', 1),
  ('Gan gà', 0),
  ('Găng tay cao su đen', 16),
  ('Găng tay nilong hộp', 48),
  ('Găng tay nilong túi', 0),
  ('Gelatin bột LHP (1kg)', 8),
  ('Gelatin lá loại 1kg', 4),
  ('Ghim', 0),
  ('Gia vị bò kho', 5),
  ('Giấy ăn nhỏ thùng 20g', 30),
  ('Giấy ăn to thùng 36g', 34),
  ('Giấy gạo', 6),
  ('Giấy lót khuôn', 1),
  ('Giấy vệ sinh (bịch 10 cuộn)', 7),
  ('Gum nặn bánh 600g', 0),
  ('Hành lá', 0),
  ('Hạnh nhân lát (thùng 11,34)', 0),
  ('Hành phi túi 1kg', 2),
  ('Hành tây', 0),
  ('Hạt bí xanh', 0),
  ('Hạt chia', 3),
  ('Hạt dẻ cười túi 500g', 21),
  ('Hạt điều', 0),
  ('Hạt lanh', 0),
  ('Hạt nêm', 1),
  ('Hạt óc chó', 0),
  ('hạt quinoa', 0),
  ('Hồng trà Shan tuyết Peso', 5),
  ('Hồng trà thượng hạng việt tuấn', 10),
  ('Hộp bông lan ruốc ĐL', 3),
  ('Hộp caramen nhỏ', 1300),
  ('Hộp caramen to', 0),
  ('Hộp chuối (dây 100c)', 5),
  ('Hộp crep trà xanh scl (DÂY 50C)', 5),
  ('Hộp cửa sổ w1600 giấy crap', 50),
  ('Hộp cửa sổ w700 giấy crap', 49),
  ('Hộp đựng bánh bao 4c DP-53 (dây 50c)', 1),
  ('Hộp đựng bánh bao nướng Quảng Đông (dây 50c)', 7),
  ('Hộp đựng bánh bò to (dây 50)', 3),
  ('Hộp đựng bánh cuộn (dây 50c)', 4),
  ('Hộp đựng bánh mật ông 4c (trứng/donut )', 216),
  ('Hộp đựng bánh mì/bánh bao', 250),
  ('Hộp đựng bánh thỏi vàng (dây 50c)', 22),
  ('Hộp đựng Cupcake vani H17 (dây 100c)', 3),
  ('Hộp đựng gato cắt C55 (dây 100c)', 7),
  ('Hộp đựng maccaron đế nâu', 0),
  ('Hộp đựng ốc kem', 2),
  ('Hộp đựng su kem H50 (dây 100c)', 1999),
  ('Hộp gato 26 (60c)', 1550),
  ('Hộp gato 30 (30c)', 450),
  ('Hộp gato 30x40', 50),
  ('Hộp gato 32', 2000),
  ('Hộp gato cắt giấy', 0),
  ('Hộp gato mini (dây 100c)', 2),
  ('Hộp giấy đựng bánh mỳ bơ đường', 50),
  ('Hộp giấy đựng da lợn đế trắng', 700),
  ('Hộp giấy nâu 2 ngăn nắp trong', 400),
  ('Hộp H23', 400),
  ('Hộp mica 40x60', 3),
  ('Hộp mica size 22', 150),
  ('Hộp mouse cốc lẻ', 50),
  ('Hộp nhựa chữ nhật 1000ml', 31),
  ('Hộp nhựa chữ nhật 750ml', 35),
  ('Hộp nhựa đáy 4 ngăn đựng cơm', 0),
  ('Hộp nhựa fk333 bao nướng/bơ tỏi 50c/túi', 150),
  ('Hộp oval red/choco/bltm (dây 50c)', 8),
  ('Hộp pizza size 19', 42),
  ('Hộp pizza size 31', 50),
  ('Hộp Sandwich vuông gấu vàng (dây 50c)', 9),
  ('Hộp tart trứng (DÂY 50C)', 2),
  ('Hộp vuông 40x40', 20),
  ('Hộp vuông BLTM', 0),
  ('Hũ đựng sốt liền nắp 2,5oz (50c/lốc)', 1),
  ('Hũ đựng sốt liền nắp 2oz (50c/lốc)', 20),
  ('Hũ sữa chua nhựa', 0),
  ('Húng lìu', 1),
  ('Hương vani LAPATELIERE', 1),
  ('Hương vani LAWAIGDA', 1),
  ('Kem béo thực vật RICH''s 454g', 88),
  ('Kem lá dứa phomai Nhất Hương', 2),
  ('Kem làm bánh vị mặn Rich''s', 12),
  ('Kem socola', 5),
  ('Kem sữa Tatua 36% 1L NZ Sky', 0),
  ('Kem sữa Tatua 36% 1LNZ HL', 120),
  ('Kem trứng 1kg', 5),
  ('Kem vivo (12 hộp)', 120),
  ('Kẹo dẻo que', 0),
  ('Kẹo đồng tiền PK', 0),
  ('Kẹo marshmallow trắng 500g', 10),
  ('Kẹo socola popit', 0),
  ('Kẹo thái kem', 0),
  ('Khăn lau', 8),
  ('Khẩu trang nhựa', 22),
  ('Khoai lang', 0),
  ('Khoai môn', 0),
  ('Khủng long bé', 0),
  ('Khủng long to PK', 0),
  ('Khung thành cầu thủ PK', 0),
  ('Kurumi nhựa PK', 0),
  ('Lá dứa', 0),
  ('Lá oregano 100g', 1),
  ('Lọ 1000ml (72c/kiện)', 72),
  ('Lọ tròn 500ml (98c/kiện)', 98),
  ('Lọ tròn 750ml (131c/thùng)', 262),
  ('Lon 500ml (171c/kiện)', 0),
  ('Lon chè 330 (thùng 258)', 0),
  ('Lon trà sữa 330ml (dây 83c)', 0),
  ('Lợn xay', 0),
  ('Lòng trắng trứng can 10Kg', 6.5),
  ('Lục trà nhài Leader', 5),
  ('Mắm tép', 8),
  ('Màng bọc thực phẩm', 9),
  ('Mascarpone', 9),
  ('Mật ong 1L', 19),
  ('Màu đỏ cherry', 1),
  ('Màu đồng tiến đen 600g', 1),
  ('Màu đồng tiến hồng cánh sen', 0),
  ('Màu lỏng đỏ', 2),
  ('Màu lỏng nâu', 0),
  ('Màu lỏng vàng', 1),
  ('Màu lỏng xanh dương', 1),
  ('Màu lỏng xanh lá', 2),
  ('Màu nước đồng tiến Ivory', 1),
  ('Màu trắng SENSIENT', 2),
  ('Men ông đầu bếp vàng (men ngọt)', 36),
  ('Mèo kity đơn PK', 0),
  ('Mì chính túi 1.8kg', 1),
  ('Miến', 4),
  ('Mít Thái', 0),
  ('Mỡ', 0),
  ('Mọc', 0),
  ('Mộc nhĩ', 1),
  ('Mochi miếng vị dâu', 8),
  ('Mochi miếng vị dừa', 8),
  ('Monin vải', 1),
  ('Mozzarella bào Argentina 1kg', 477),
  ('Mũ ivory 3d mix siêu nhân / công chúa', 1),
  ('Mùi ta', 0),
  ('Muối sấy Ngọc Yến 250g/túi', 9),
  ('Muối tinh 500gr', 52),
  ('Mứt Berino chanh dây (1kg)', 5),
  ('Mứt Berino dâu tây (1kg)', 3),
  ('Mứt long nhãn BODUO', 2),
  ('Mứt nhân chuối nhãn vàng (5kg)', 3),
  ('Mứt xác việt quất Berrino 950G', 5),
  ('Mứt xoài TQ', 1),
  ('Nấm đông cô', 0),
  ('Nấm đùi gà', 0),
  ('Nấm hương', 0),
  ('Nến số vàng', 2751),
  ('Nến tăm lẻ', 59),
  ('Nến xoắn', 5),
  ('Nguyên cám thô', 18),
  ('Nhân cốm tươi xào', 3),
  ('Nhân dừa non', 5),
  ('Nhân kem vị sầu riêng', 23),
  ('Nhân kem vị socola', 20),
  ('Nhân kem vị trứng muối', 12),
  ('Nhân phomai', 15),
  ('Nhân phomai cháy', 17),
  ('Nhân sen tươi', 0),
  ('Nhân sữa chua', 15),
  ('Nhân thập cẩm', 5),
  ('Nhân trứng dẻo NTT', 20),
  ('Nho đen không hạt Úc', 2.448),
  ('Nho khô', 4.5),
  ('Nho Xanh', 0),
  ('Nước cam lon', 2),
  ('Nước cốt dừa (thùng 12 hộp)', 30),
  ('Nước mắm chai 1.2l', 9),
  ('Nước nấu tàu hũ', 5),
  ('Nước phủ bóng', 0),
  ('Nước quét mặt bánh can 2L', 9),
  ('Nước rửa bát', 15),
  ('Nước tương magi', 9),
  ('Ô tô 6c', 0),
  ('Oliu đen olive', 1),
  ('Oliu xanh', 2),
  ('Ống hút', 42),
  ('Ớt bột Hàn Quốc', 0),
  ('Ớt sừng', 0),
  ('Ớt trưng dầu', 8),
  ('Oto suvs PK', 0),
  ('Pháo phụt', 220),
  ('Phôi lúa mì', 90),
  ('Phomai con bò cười vinamil', 3),
  ('Phomai lát', 6),
  ('Phomai Mozzarella bào 1kg', 0),
  ('Phụ gia bánh mỳ ngọt ibis', 28),
  ('Quả anh đào không cuống', 1),
  ('Quả bóng đá-PK', 0),
  ('Quả dứa', 0),
  ('Quả dưa lưới', 0),
  ('Quả nhãn - Chè', 0),
  ('Quả quất', 0),
  ('Quả việt quất khô', 5.2),
  ('Quây thành nhiều chi tiết', 5),
  ('Quây trong size 10', 11),
  ('Quây trong size 12', 1),
  ('Quây trong size 8', 1),
  ('Ruốc gà cay túi 1kg', 25),
  ('Ruốc rong biển túi 1kg', 8),
  ('Ruốc trắng', 0),
  ('Rượu rum nội', 0),
  ('Ruy chanel-PK', 0),
  ('Ruy von PK', 0),
  ('Sao đường-PK', 0),
  ('Sầu riêng nguyên chất 1KG/TÚI', 79),
  ('Sauce dưa lưới BODUO', 1),
  ('Sauce ổi BODUO hũ 1kg', 1),
  ('Sen tươi', 20),
  ('Set 4 (hộp 4 chi tiết)', 70),
  ('Set 6 (hộp 4 chi tiết)', 50),
  ('Set khay kẹo nougat', 10),
  ('Siêu nhân nhựa (7 con) PK', 0),
  ('Sinh tố Berrino chanh dây 1L', 5),
  ('Sinh tố Berrino dâu tây 1L', 3),
  ('Sinh tố dâu osterberg', 4),
  ('Sinh tố mãng cầu goldenfarm', 3),
  ('Sinh tố trái cây maomao', 1),
  ('Sinh tố xoài Osterber', 3),
  ('Siro đào dingfong', 1),
  ('Siro Davinci Hazelnut', 1),
  ('Siro hạnh nhân rang', 1),
  ('Siro Maulin vị dưa lưới 2,5kg', 0),
  ('Siro monin lá dứa 700ml', 1),
  ('Siro nhiệt đới', 2),
  ('Siro xoài dingfong', 1),
  ('Sô-cô-la N.Chất đen Ghana thanh 1kg', 8),
  ('Socola chíp trắng W13C (2.5kg)', 2),
  ('Socola dâu túi 1kg puratos carat', 3),
  ('Socola đen D013 thanh 2kg', 3),
  ('Socola đen- Men mộc', 6.5),
  ('Socola GanaFarm trắng CW005 (1kg)', 23),
  ('Socola hạt chíp đen D07C (2,5kg)', 4),
  ('Socola hương cam loại 1kg puratos carat', 3),
  ('Socola hương việt quất loại 1kg', 3),
  ('Socola nút grand-place puratos túi 1kg', 2),
  ('Socola sệt nâu M081 (4kg/xô)', 1),
  ('Socola sệt trắng W082 (4kg/xô)', 1),
  ('Sốt mayonnaise xô 3kg', 0),
  ('Sốt nấm cục Truffle La Sicilia 500g', 0),
  ('Sốt salat bánh mỳ ngọt', 8),
  ('Sốt ướp xá xíu', 21),
  ('Sữa bột', 0),
  ('Sữa bột béo tan nhanh NZ', 25),
  ('Sữa bột Cô gái Hà Lan', 0),
  ('Sữa chua ăn', 25),
  ('Sữa đặc ngôi sao phương nam', 7),
  ('Sữa đặc ông thọ đỏ 1284g', 15),
  ('Sữa tươi H-milk tiệt trùng nguyên kem 3.5% (12h/thùng)', 60),
  ('Sunup ổi', 1),
  ('Sunup vải', 0),
  ('Súp lơ', 0),
  ('Táo đỏ 1,2kg', 7),
  ('Thạch dừa thô loại 1kg/túi', 7),
  ('Thẻ meka happy birthday (túi 10c)', 0),
  ('Thìa ăn chè 100c/túi', 57),
  ('Thìa nhựa (2kg)', 6),
  ('Thịt bắp', 0),
  ('Thịt Phệ', 0),
  ('Thịt vai giòn', 0),
  ('Tinh bột khoai tây (400g)', 4),
  ('Tinh bột sắn 25kg', 1),
  ('Tinh chất lá dứa 6 lọ/lốc', 11),
  ('Tỏi bóc sẵn', 0),
  ('Tôm tươi', 0),
  ('Top pop Bơ BOS lỏng 18kg HN', 1),
  ('Trà gạo', 6),
  ('Trà gạo rang', 1),
  ('Trà ô long khói', 2),
  ('Trà ô long nướng', 0),
  ('Trà ô long quế hoa Việt Tuấn-Chè', 3),
  ('Trà ô long xanh queen', 1),
  ('Trà Olong nhài việt tuấn', 5),
  ('Trà thái xanh', 3),
  ('Trà xanh nhài việt tuấn', 2),
  ('Trân châu đen Queen', 2),
  ('Trân châu hoàng kim', 10),
  ('Trân châu sợi Toco', 14),
  ('Trân châu trắng 3Q', 3),
  ('Trứng cút', 0),
  ('Trứng muối (100q/túi)', 0),
  ('Trứng muối 30q/khay', 16),
  ('Trứng muối vụn', 4),
  ('Túi 16x23', 1),
  ('Túi bánh mì nguyên cám', 100),
  ('Túi bánh mì xoắn', 250),
  ('Túi bánh mỳ gối 50c/tập', 200),
  ('Túi chéo bắt kem loại to (100c tập)', 1),
  ('Túi đóng chè sỉ 1kg', 12),
  ('Túi giữ nhiệt chum chum', 1630),
  ('Túi hoa đựng set 4', 36),
  ('Túi hút chân không', 0),
  ('Túi hút chân không đá', 0),
  ('Túi hút chân không pizza', 49),
  ('Túi nilong đỏ', 8),
  ('Túi nilong rác đen', 6),
  ('Túi nilong trắng bé', 5),
  ('Túi nilong trắng nhỡ', 15),
  ('Túi nilong trắng to', 6),
  ('Túi nilong vàng', 3),
  ('Túi nilong xanh', 2),
  ('Túi ô xi trung thu', 0),
  ('Túi quẩy ngàn lớp', 0),
  ('Túi zip bizonzon', 0),
  ('Túi zip số 2', 0),
  ('Tương cà (can 2L)', 0),
  ('Ức gà', 0),
  ('Vỏ mochi 2 cái X202 (dây 100c)', 150),
  ('Vừng đen', 0),
  ('Vừng trắng', 4),
  ('Xà lách', 0),
  ('Xả tươi', 0),
  ('Xe cẩu to -PK', 0),
  ('Xì dầu đặc biệt LEEKUMKEE (Can 2l)', 3),
  ('Xoài cát chu', 0),
  ('Xôi lá nếp cốt dừa', 5),
  ('Xúc Xích', 0),
  ('Yến mạch', 0);

-- Upsert vào stock_opening_adj: match sản phẩm theo tên (case-insensitive)
INSERT INTO stock_opening_adj (product_name, year, month, adj_qty, updated_by)
SELECT
  p.name,
  2026,
  5,
  GREATEST(0, t.ton_cuoi),
  'admin-import-t4-cuoi'
FROM tmp_ton_dau_t5 t
JOIN products p ON lower(p.name) = lower(t.ten_san_pham)
WHERE p.is_active = true
ON CONFLICT (product_name, year, month)
  DO UPDATE SET
    adj_qty    = EXCLUDED.adj_qty,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

COMMIT;

-- ── Kiểm tra sau import ──────────────────────────────────────
-- Số dòng đã upsert:
SELECT COUNT(*) AS da_upsert
FROM stock_opening_adj
WHERE year = 2026 AND month = 5;

-- Tên trong tmp không khớp products (cần kiểm tra chính tả):
SELECT t.ten_san_pham
FROM tmp_ton_dau_t5 t
LEFT JOIN products p ON lower(p.name) = lower(t.ten_san_pham)
WHERE p.id IS NULL
ORDER BY t.ten_san_pham;
