-- ============================================================
-- reset_and_import_products.sql
-- Chạy trong Supabase Dashboard → SQL Editor
-- CẢNH BÁO: XÓA TOÀN BỘ products, batches, batch_deductions
-- ============================================================

BEGIN;

-- 1. Xóa dữ liệu cũ (theo thứ tự FK)
DELETE FROM batch_deductions;
DELETE FROM batches;
DELETE FROM products;

-- 2. Insert toàn bộ sản phẩm mới
WITH u AS (SELECT id FROM auth.users ORDER BY created_at LIMIT 1)
INSERT INTO products (code, name, category, unit, cost_price, sell_price, stock_qty, min_stock, is_active, created_by, created_at)
SELECT v.code, v.name, v.category, v.unit, v.cost_price, 0, 0, 0, true, u.id, NOW()
FROM (VALUES
  -- ── NGUYÊN LIỆU ──────────────────────────────────────────
  ('NL0305',          'Bánh mỳ dài làm pate',                             'Nguyên liệu', 'Cái',    0),
  ('NL-OREO',         'Bánh oreo',                                         'Nguyên liệu', 'Thanh',  9000),
  ('NL-DAHEO',        'Bì lợn',                                            'Nguyên liệu', 'Kg',     0),
  ('NL0282',          'Bơ cán 82% đông lạnh 2kg Grand Fermage',           'Nguyên liệu', 'Kg',     314814),
  ('NL0144',          'Bơ cán',                                            'Nguyên liệu', 'Kg',     0),
  ('NL-BOQUA-DEO',    'Bơ quả cấp đông',                                  'Nguyên liệu', 'Túi',    105000),
  ('NL0300',          'Bơ hạt phỉ golden farm',                           'Nguyên liệu', 'Lọ',     0),
  ('NL-BO0026HL',     'Bơ New Anchor 4x5kg',                              'Nguyên liệu', 'Thùng',  264000),
  ('NL0145',          'Bơ ngọt dạng miếng (10 túi / thùng)',              'Nguyên liệu', 'Kiện',   1350000),
  ('NL0190',          'Bò xay',                                            'Nguyên liệu', 'Kg',     0),
  ('NL-BOTSU-SKY',    'Bột su kem cremyvit 5kg/túi',                      'Nguyên liệu', 'Túi',    575100),
  ('NL-BOTTAYAKI-NH', 'Bột vỏ bánh Taiyaki Nhật Bản túi 1kg',            'Nguyên liệu', 'Túi',    73000),
  ('NL0233',          'Bột baking soda',                                   'Nguyên liệu', 'Hộp',    35000),
  ('NL-BOTBAP-SKY',   'Bột bắp (25kg)',                                   'Nguyên liệu', 'Kg',     23000),
  ('NL-BOTBIENTINH',  'Bột biến tính',                                     'Nguyên liệu', 'Kg',     0),
  ('NL-GIAVIBOKHO',   'Gia vị bò kho',                                     'Nguyên liệu', 'Gói',    10000),
  ('NL-BOTBHX-MB',    'Bột bông hồng 25kg',                               'Nguyên liệu', 'Bao',    16600),
  ('NL0243',          'Bột cà ri',                                         'Nguyên liệu', 'Túi',    170000),
  ('NL-BOTKAKAO-OV',  'Bột cacao túi 1kg',                                'Nguyên liệu', 'Túi',    295000),
  ('NL-BOTCHANH',     'Bột chanh 400g/túi',                               'Nguyên liệu', 'Túi',    120000),
  ('NL-BOTCX',        'Bột chiên xù gói 1kg',                             'Nguyên liệu', 'Gói',    40000),
  ('NL-BOTCONVOI-LN', 'Bột con voi',                                       'Nguyên liệu', 'Bao',    745000),
  ('NL-BOTKTIM',      'Bột khoai tím (túi 500g)',                         'Nguyên liệu', 'Túi',    0),
  ('NL-BOTKIMSON-SKY','Bột Kim Sơn',                                       'Nguyên liệu', 'Bao',    0),
  ('NL-BOTBIZON-TH',  'Bột làm bizonzon Thanh Hóa',                       'Nguyên liệu', 'Bao',    0),
  ('NL-BOTMOCHI-LN',  'Bột mochi túi 1kg',                                'Nguyên liệu', 'Túi',    0),
  ('NL-BOT999-MB',    'Bột mỳ 999 (bao 25kg)',                            'Nguyên liệu', 'Bao',    487500),
  ('NL-BOTCONA-SKY',  'Bột mỳ Hàn Quốc Cona 1kg',                       'Nguyên liệu', 'Túi',    100000),
  ('NL-BMNCBOLD',     'Bột mỳ nguyên cám Bods red mill 2,27kg/túi',      'Nguyên liệu', 'Túi',    0),
  ('NL-BOTNANG-PHK',  'Bột năng túi 1kg',                                 'Nguyên liệu', 'Túi',    30000),
  ('NL-BOTCHE-DEO',   'Bột nấu chè 1kg',                                  'Nguyên liệu', 'Túi',    47000),
  ('NL-BOTNEP',       'Bột nếp làm bánh dẻo 10kg/túi',                   'Nguyên liệu', 'Túi',    0),
  ('NL-NEPTHAI-PHK',  'Bột nếp Thái 1kg bizonzon',                        'Nguyên liệu', 'Túi',    40000),
  ('NL-BOTNGHE',      'Bột nghệ',                                          'Nguyên liệu', 'Gói',    0),
  ('NL-BOTNOIMAURI-SKY','Bột nổi làm bánh AB mauri',                      'Nguyên liệu', 'Túi',    0),
  ('NL-BOTNOIBICO-SKY','Bột nổi UCC Bico hộp 1kg',                        'Nguyên liệu', 'Hộp',    62000),
  ('NL-VUNOREO',      'Bột oreo',                                          'Nguyên liệu', 'Túi',    165000),
  ('NL-SOCVANG-DEO',  'Bột rau câu Sóc Vàng',                             'Nguyên liệu', 'Hộp',    59000),
  ('NL-AGAR-PHK',     'Bột rong câu giòn - Agar',                         'Nguyên liệu', 'Gói',    4000),
  ('NL-BOTSUTU-PHK',  'Bột sư tử 1kg/túi',                               'Nguyên liệu', 'Túi',    0),
  ('NL-BSALMER941-DEO','Bột sữa Almer 941 túi 900g',                      'Nguyên liệu', 'Gói',    74000),
  ('NL-BSALMER941B-DEO','Bột sữa Almer941 bao',                           'Nguyên liệu', 'Bao',    1682000),
  ('NL-BOTSKMON-DEO', 'Bột sữa khoai môn',                                'Nguyên liệu', 'Túi',    0),
  ('NL-BOTSS',        'Bột sương sáo 50g/túi',                            'Nguyên liệu', 'Túi',    0),
  ('NL-BOTTOI',       'Bột tỏi',                                           'Nguyên liệu', 'Lọ',     0),
  ('B-MATCHA DL-OV',  'Bột trà xanh matcha ĐL 500g',                      'Nguyên liệu', 'Túi',    375000),
  ('B-MATCHA UJI-NH', 'Bột trà xanh Uji Ceremonial 50g',                  'Nguyên liệu', 'Túi',    99450),
  ('NL-BOTCHOCO-OV',  'Bột trộn sẵn bánh ẩm sô-cô-la túi 5kg',          'Nguyên liệu', 'Túi',    106812),
  ('NL-BOTRED-OV',    'Bột trộn sẵn bánh redvelvet túi 5kg',             'Nguyên liệu', 'Túi',    98604),
  ('NL-BOTTMGUMI',    'Bột trứng muối GUMI EGG túi 1kg',                 'Nguyên liệu', 'Túi',    0),
  ('NL-BOTXDX-MB',    'Bột xe đạp xanh / blue2 (25kg)',                   'Nguyên liệu', 'Bao',    16200),
  ('NL0274',          'Cà chua',                                           'Nguyên liệu', 'Kg',     0),
  ('NL0162',          'Cà phê phố đen',                                   'Nguyên liệu', 'Hộp',    40000),
  ('NL0155',          'Cà ri đen',                                         'Nguyên liệu', 'Hộp',    0),
  ('NL0156',          'Cam',                                               'Nguyên liệu', 'Kg',     56000),
  ('NL0224',          'Cam sấy khô',                                       'Nguyên liệu', 'Túi',    0),
  ('NL0161',          'Cam vàng TQ',                                       'Nguyên liệu', 'Kg',     39000),
  ('NL0087',          'Chân gà sả ớt tiến vua Sevifood túi 850g',        'Nguyên liệu', 'Túi',    88270),
  ('NL0227',          'Chanh tươi',                                        'Nguyên liệu', 'Kg',     0),
  ('NL0010',          'Chất ổn định bico không màu (20kg)',               'Nguyên liệu', 'Xô',     1020000),
  ('NL0158',          'Cherry',                                            'Nguyên liệu', 'Kg',     184000),
  ('NL0223',          'Chuối quả',                                         'Nguyên liệu', 'Khay',   0),
  ('NL0270',          'Cơm dừa',                                           'Nguyên liệu', 'Túi',    0),
  ('NL0261',          'Cốm hạt',                                           'Nguyên liệu', 'Kg',     0),
  ('NL-CHNM',         'Cốm hạt nhiều màu',                                'Nguyên liệu', 'Lọ',     0),
  ('NL0124',          'Cốt café',                                          'Nguyên liệu', 'Chai',   0),
  ('NL0183',          'Cream Alternative Anchor 1L',                       'Nguyên liệu', 'Hộp',    140000),
  ('NL0073',          'Cream cheese Dairymont 2Kg',                       'Nguyên liệu', 'Kg',     185000),
  ('NL0135',          'Creamy (12 hộp)',                                   'Nguyên liệu', 'Hộp',    69500),
  ('NL0168',          'Củ hành khô',                                       'Nguyên liệu', 'Kg',     50000),
  ('NL0222',          'Củ tỏi',                                            'Nguyên liệu', 'Kg',     0),
  ('NL0178',          'Cùi bưởi 1kg',                                     'Nguyên liệu', 'Túi',    70000),
  ('NL0198',          'Đá hút chân không lẻ',                             'Nguyên liệu', 'Túi',    0),
  ('NL0288',          'Đá viên',                                           'Nguyên liệu', 'Túi',    8000),
  ('NL0211',          'Đác rim',                                           'Nguyên liệu', 'Túi',    0),
  ('NL0024',          'Dấm trắng 500ml',                                   'Nguyên liệu', 'Chai',   10000),
  ('NL0012',          'Dầu ăn Orchid 7,5 lít/can',                        'Nguyên liệu', 'Can',    275000),
  ('NL0148',          'Đậu đỏ 3kg',                                       'Nguyên liệu', 'Túi',    180000),
  ('NL0204',          'Đậu đỏ lon',                                        'Nguyên liệu', 'Lon',    58000),
  ('NL0244',          'Dầu hào',                                           'Nguyên liệu', 'Chai',   0),
  ('NL0025',          'Dầu hướng dương loại 1L',                          'Nguyên liệu', 'Chai',   53005),
  ('NL0273',          'Dâu hộp',                                           'Nguyên liệu', 'Hộp',    25000),
  ('NL0122',          'Dầu tê',                                            'Nguyên liệu', 'Chai',   47000),
  ('NL0159',          'Dâu tươi',                                          'Nguyên liệu', 'Hộp',    18888),
  ('NL0208',          'Dừa non',                                           'Nguyên liệu', 'Kg',     65000),
  ('NL0150',          'Dừa sấy vụn',                                       'Nguyên liệu', 'Túi',    0),
  ('NL0056',          'Đường đen nữ hoàng Biên Hòa',                     'Nguyên liệu', 'Kg',     48652),
  ('NL0009',          'Đường phèn bao 10kg',                              'Nguyên liệu', 'Bao',    300000),
  ('NL0014',          'Đường thốt nốt túi 1kg',                          'Nguyên liệu', 'Túi',    44000),
  ('NL0218',          'Đường thốt nốt túi 2,5kg',                        'Nguyên liệu', 'Túi',    0),
  ('NL0106',          'Đường trắng 50kg/bao',                             'Nguyên liệu', 'Kg',     19500),
  ('NL0029',          'Đường xay (túi 1kg)',                              'Nguyên liệu', 'Túi',    38000),
  ('NL0210',          'Falu mật ong can 2 lít',                           'Nguyên liệu', 'Can',    222000),
  ('NL0302',          'Gan gà',                                            'Nguyên liệu', 'Kg',     0),
  ('NL0126',          'Gelatin bột LHP (1kg)',                             'Nguyên liệu', 'Kg',     285000),
  ('NL0026',          'Gelatin lá loại 1kg',                              'Nguyên liệu', 'Hộp',    660000),
  ('NL0250',          'Gia vị gà',                                         'Nguyên liệu', 'Gói',    0),
  ('NL0249',          'Gia vị phở bò',                                    'Nguyên liệu', 'Gói',    0),
  ('NL0229',          'Hành lá',                                           'Nguyên liệu', 'Kg',     50000),
  ('NL0035',          'Hạnh nhân bột',                                     'Nguyên liệu', 'Kg',     255000),
  ('NL0138',          'Hạnh nhân hạt',                                     'Nguyên liệu', 'Kg',     0),
  ('NL0096',          'Hạnh nhân lát (thùng 11,34)',                      'Nguyên liệu', 'Thùng',  2892000),
  ('NL0166',          'Hành phi lọ',                                       'Nguyên liệu', 'Lọ',     50000),
  ('NL0044',          'Hành phi túi 1kg',                                  'Nguyên liệu', 'Túi',    0),
  ('NL0185',          'Hành tây',                                          'Nguyên liệu', 'Kg',     50000),
  ('NL0140',          'Hạt bí xanh',                                       'Nguyên liệu', 'Kg',     0),
  ('NL0226',          'Hạt chia',                                          'Nguyên liệu', 'Túi',    60000),
  ('NL0095',          'Hạt dẻ cười túi 500g',                             'Nguyên liệu', 'Túi',    0),
  ('NL0114',          'Hạt điều',                                          'Nguyên liệu', 'Kg',     180000),
  ('NL0167',          'Hạt tiêu',                                          'Nguyên liệu', 'Kg',     200000),
  ('NL0265',          'Hồng trà Shan tuyết Peso',                         'Nguyên liệu', 'Gói',    0),
  ('NL0285',          'Hồng trà thượng hạng việt tuấn',                  'Nguyên liệu', 'Túi',    96000),
  ('NL0217',          'Húng lìu',                                          'Nguyên liệu', 'Gói',    150000),
  ('NL0298',          'Hương vani LAPATELIERE',                            'Nguyên liệu', 'Chai',   0),
  ('NL0299',          'Hương vani LAWAIGDA',                              'Nguyên liệu', 'Chai',   0),
  ('NL0262',          'Kem lá dứa phomai Nhất Hương',                    'Nguyên liệu', 'Hộp',    49000),
  ('NL0268',          'Kem làm bánh vị mặn Rich''s',                      'Nguyên liệu', 'Hộp',    89298),
  ('NL-KEMSCL-OV',    'Kem socola',                                        'Nguyên liệu', 'Thùng',  874000),
  ('NL0272',          'Kem sữa Meadow Fresh 1L NZ',                       'Nguyên liệu', 'Lít',    145800),
  ('NL-KST36%',       'Kem sữa Tatua 36% 1L NZ Sky',                     'Nguyên liệu', 'Lít',    160000),
  ('NL0074',          'Kem sữa Tatua 36% 1LNZ HL',                       'Nguyên liệu', 'Lít',    129000),
  ('NL0084',          'Kem sữa Whip & Cook ArlaPro',                      'Nguyên liệu', 'Hộp',    128200),
  ('NL0060',          'Kem trứng 1kg',                                     'Nguyên liệu', 'Hộp',    70000),
  ('NL0111',          'Kem vivo (12 hộp)',                                 'Nguyên liệu', 'Thùng',  828000),
  ('NL-KEMRICH-OV',   'Kem béo thực vật RICH''s 454g',                   'Nguyên liệu', 'Hộp',    31030),
  ('NL0160',          'Kẹo lạc',                                           'Nguyên liệu', 'Kg',     60000),
  ('NL0078',          'Kẹo marshmallow trắng 500g',                       'Nguyên liệu', 'Túi',    35000),
  ('NL0059',          'Khô gà',                                            'Nguyên liệu', 'Kg',     180000),
  ('NL0186',          'Khoai lang',                                        'Nguyên liệu', 'Kg',     35000),
  ('NL0216',          'Lá dứa',                                            'Nguyên liệu', 'Kg',     30000),
  ('NL0175',          'Lá oregano 100g',                                   'Nguyên liệu', 'Kg',     105000),
  ('NL0147',          'Lava nhân trứng muối chảy túi 3kg NTT',           'Nguyên liệu', 'Túi',    0),
  ('NL0188',          'Lợn xay',                                           'Nguyên liệu', 'Kg',     0),
  ('NL0121',          'Lòng trắng trứng can 10Kg',                        'Nguyên liệu', 'Kg',     22000),
  ('NL0258',          'Lục trà nhài Leader',                              'Nguyên liệu', 'Túi',    120000),
  ('NL0068',          'Macca',                                             'Nguyên liệu', 'Bao',    0),
  ('NL0181',          'Mắm tép',                                           'Nguyên liệu', 'Chai',   0),
  ('NL0134',          'Mascarpone',                                        'Nguyên liệu', 'Gói',    269500),
  ('NL0194',          'Màu lỏng đỏ',                                      'Nguyên liệu', 'Kg',     146000),
  ('NL0193',          'Màu lỏng nâu',                                     'Nguyên liệu', 'Kg',     146000),
  ('NL0197',          'Màu lỏng vàng',                                    'Nguyên liệu', 'Kg',     146000),
  ('NL0195',          'Màu lỏng xanh dương',                              'Nguyên liệu', 'Kg',     146000),
  ('NL0196',          'Màu lỏng xanh lá',                                 'Nguyên liệu', 'Kg',     146000),
  ('NL0089',          'Màu nước đồng tiến Ivory',                         'Nguyên liệu', 'Chai',   45000),
  ('NL0090',          'Màu nước đồng tiến vàng tươi 600g',               'Nguyên liệu', 'Chai',   113000),
  ('NL0301',          'Màu trắng SENSIENT',                               'Nguyên liệu', 'Lọ',     0),
  ('NL0283',          'Mè xay 500g',                                       'Nguyên liệu', 'Kg',     200000),
  ('NL0023',          'Men ông đầu bếp vàng (men ngọt)',                  'Nguyên liệu', 'Túi',    64500),
  ('NL0058',          'Mì chính túi 1.8kg',                               'Nguyên liệu', 'Kg',     55000),
  ('NL0125',          'Mì chính túi 1 kg',                                'Nguyên liệu', 'Túi',    115000),
  ('NL0191',          'Miến',                                              'Nguyên liệu', 'Túi',    50000),
  ('NL0172',          'Mít Thái',                                          'Nguyên liệu', 'Khay',   50000),
  ('NL0304',          'Mỡ',                                               'Nguyên liệu', 'Kg',     0),
  ('NL0109',          'Mỡ đường',                                         'Nguyên liệu', 'Kg',     0),
  ('NL0189',          'Mọc',                                              'Nguyên liệu', 'Kg',     0),
  ('NL0065',          'Mochi miếng vị dâu',                               'Nguyên liệu', 'Túi',    28000),
  ('NL0066',          'Mochi miếng vị dừa',                               'Nguyên liệu', 'Túi',    28000),
  ('NL0294',          'Monin vải',                                         'Nguyên liệu', 'Chai',   0),
  ('PL-PMBAO',        'Phomai Mozzarella bào 1kg',                        'Nguyên liệu', 'Túi',    175000),
  ('NL0278',          'Mozzarella bào Argentina 1kg',                     'Nguyên liệu', 'Kg',     160000),
  ('NL0037',          'Muối sấy Ngọc Yến 250g/túi',                      'Nguyên liệu', 'Túi',    0),
  ('NL0036',          'Muối tinh 500gr',                                   'Nguyên liệu', 'Túi',    7500),
  ('NL0082',          'Mứt Berino chanh dây (1kg)',                       'Nguyên liệu', 'Lọ',     78000),
  ('NL0083',          'Mứt Berino dâu tây (1kg)',                         'Nguyên liệu', 'Lọ',     77000),
  ('NL0067',          'Mứt nhân chuối nhãn vàng (5kg)',                  'Nguyên liệu', 'Xô',     475000),
  ('NL0132',          'Mứt xác việt quất Berrino 950G',                  'Nguyên liệu', 'Hộp',    97000),
  ('NL0295',          'Mứt xoài TQ',                                      'Nguyên liệu', 'Hũ',     0),
  ('NL0077',          'Nấm hương',                                         'Nguyên liệu', 'Kg',     250000),
  ('NL0241',          'Ngũ vị hương',                                      'Nguyên liệu', 'Hộp',    0),
  ('NL0103',          'Nhân cốm tươi xào',                                'Nguyên liệu', 'Kg',     0),
  ('NL0102',          'Nhân dứa',                                          'Nguyên liệu', 'Kg',     0),
  ('NL0104',          'Nhân dừa non',                                      'Nguyên liệu', 'Kg',     0),
  ('NL0045',          'Nhân hạt dẻ túi 1kg',                              'Nguyên liệu', 'Túi',    0),
  ('NL0064',          'Nhân kem vị sầu riêng',                            'Nguyên liệu', 'Gói',    80000),
  ('NL0063',          'Nhân kem vị socola',                               'Nguyên liệu', 'Túi',    82000),
  ('NL0062',          'Nhân kem vị trứng muối',                           'Nguyên liệu', 'Gói',    88000),
  ('NL0070',          'Nhân phomai',                                       'Nguyên liệu', 'Túi',    83000),
  ('NL0151',          'Nhân phomai cháy',                                  'Nguyên liệu', 'Túi',    82000),
  ('NL0152',          'Nhân sữa chua',                                     'Nguyên liệu', 'Túi',    0),
  ('NL0174',          'Nhân trứng dẻo NTT',                               'Nguyên liệu', 'Kg',     0),
  ('NL0271',          'Nho đen không hạt Úc',                             'Nguyên liệu', 'Kg',     239000),
  ('NL0033',          'Nho khô',                                           'Nguyên liệu', 'Kg',     115000),
  ('NL0076',          'Nước cốt dừa (thùng 12 hộp)',                     'Nguyên liệu', 'Hộp',    70000),
  ('NL0057',          'Nước mắm chai 1.2l',                               'Nguyên liệu', 'Chai',   62000),
  ('NL0075',          'Nước mắm chai 750ml',                              'Nguyên liệu', 'Chai',   55000),
  ('NL0200',          'Nước nấu tàu hũ',                                  'Nguyên liệu', 'Túi',    45000),
  ('NL0225',          'Nước phủ bóng',                                     'Nguyên liệu', 'Xô',     0),
  ('NL0048',          'Nước quét mặt bánh can 2L',                       'Nguyên liệu', 'Can',    0),
  ('NL0245',          'Nước tương magi',                                   'Nguyên liệu', 'Chai',   0),
  ('NL0296',          'Oliu đen olive',                                    'Nguyên liệu', 'Hũ',     0),
  ('NL0232',          'Ớt bột Hàn Quốc',                                  'Nguyên liệu', 'Túi',    0),
  ('NL0252',          'Ớt khô',                                            'Nguyên liệu', 'Kg',     0),
  ('NL0248',          'Ớt sừng',                                           'Nguyên liệu', 'Kg',     0),
  ('NL0123',          'Ớt trưng dầu',                                      'Nguyên liệu', 'Chai',   65000),
  ('NL0235',          'Phomai Morazela chưa bào 5kg',                     'Nguyên liệu', 'Kg',     170000),
  ('NL0246',          'Phomai con bò cười vinamil',                       'Nguyên liệu', 'Hộp',    27000),
  ('NL0136',          'Phomai lát',                                        'Nguyên liệu', 'Kg',     225000),
  ('NL0003',          'Phụ gia bánh mỳ ngọt ibis',                       'Nguyên liệu', 'Túi',    46000),
  ('NL0142',          'Phụ gia bánh mỳ Unipan (1kg)',                    'Nguyên liệu', 'Kg',     0),
  ('NL0133',          'Quả anh đào không cuống',                          'Nguyên liệu', 'Túi',    190000),
  ('NL0207',          'Quả bơ',                                            'Nguyên liệu', 'Kg',     105000),
  ('NL0247',          'Quả quất',                                          'Nguyên liệu', 'Kg',     0),
  ('NL0032',          'Quả việt quất khô',                                'Nguyên liệu', 'Kg',     180000),
  ('NL0149',          'Quế',                                               'Nguyên liệu', 'Kg',     0),
  ('NL0307',          'Riềng',                                             'Nguyên liệu', 'Kg',     0),
  ('NL0042',          'Ruốc gà cay túi 1kg',                              'Nguyên liệu', 'Túi',    250000),
  ('NL0043',          'Ruốc rong biển túi 1kg',                           'Nguyên liệu', 'Túi',    0),
  ('NL0180',          'Ruốc trắng',                                        'Nguyên liệu', 'Kg',     550000),
  ('NL0277',          'Rượu rum nội',                                      'Nguyên liệu', 'Chai',   130000),
  ('NL-SAU-MHK',      'Sầu riêng nguyên chất 1KG/TÚI',                  'Nguyên liệu', 'Túi',    150000),
  ('NL-OIBODUO',      'Sauce ổi BODUO hũ 1kg',                           'Nguyên liệu', 'Chai',   148000),
  ('NL-SDOTD',        'Sữa đặc ông thọ đỏ 1284g',                       'Nguyên liệu', 'Hộp',    75924),
  ('NL-SENHUE',       'Sen tươi',                                          'Nguyên liệu', 'Kg',     235000),
  ('NL0130',          'Sinh tố Berrino chanh dây 1L',                    'Nguyên liệu', 'Chai',   90000),
  ('NL0131',          'Sinh tố Berrino dâu tây 1L',                      'Nguyên liệu', 'Chai',   86000),
  ('NL0286',          'Sinh tố dâu osterberg',                            'Nguyên liệu', 'Chai',   109000),
  ('NL0293',          'Sinh tố mãng cầu goldenfarm',                      'Nguyên liệu', 'Chai',   140000),
  ('NL0292',          'Sinh tố trái cây maomao',                          'Nguyên liệu', 'Chai',   0),
  ('NL0239',          'Sinh tố việt quất',                                 'Nguyên liệu', 'Chai',   120000),
  ('NL0238',          'Sinh tố xoài Osterber',                            'Nguyên liệu', 'Chai',   140000),
  ('NL0291',          'Siro đào dingfong',                                 'Nguyên liệu', 'Chai',   0),
  ('NL0259',          'Siro Maulin vị dưa lưới 2,5kg',                   'Nguyên liệu', 'Chai',   225000),
  ('NL0263',          'Siro monin lá dứa 700ml',                         'Nguyên liệu', 'Chai',   267000),
  ('NL0290',          'Siro xoài dingfong',                                'Nguyên liệu', 'Chai',   82000),
  ('NL0127',          'Socola chíp trắng W13C (2.5kg)',                  'Nguyên liệu', 'Kg',     144612),
  ('NL0021',          'Socola compound hạt đen 1kg van hauten',          'Nguyên liệu', 'Túi',    0),
  ('NL0017',          'Socola dâu túi 1kg puratos carat',                'Nguyên liệu', 'Túi',    0),
  ('NL0117',          'Socola đen D013 thanh 2kg',                       'Nguyên liệu', 'Kg',     129384),
  ('NL0018',          'Socola GanaFarm trắng CW005 (1kg)',               'Nguyên liệu', 'Túi',    96000),
  ('NL0027',          'Socola hạt chíp đen D07C (2,5kg)',               'Nguyên liệu', 'Hộp',    142452),
  ('NL0019',          'Socola hương cam loại 1kg puratos carat',         'Nguyên liệu', 'Túi',    0),
  ('NL0020',          'Socola hương việt quất loại 1kg',                 'Nguyên liệu', 'Túi',    0),
  ('NL0022',          'Socola nguyên chất trắng 1kg grand-place puratos','Nguyên liệu', 'Túi',    0),
  ('NL0016',          'Socola nút grand-place puratos túi 1kg',          'Nguyên liệu', 'Túi',    0),
  ('NL0128',          'Socola sệt nâu M081 (4kg/xô)',                   'Nguyên liệu', 'Kg',     144720),
  ('NL0129',          'Socola sệt trắng W082 (4kg/xô)',                 'Nguyên liệu', 'Kg',     135540),
  ('NL0047',          'Sốt mayonnaise xô 3kg',                           'Nguyên liệu', 'Xô',     230000),
  ('NL0071',          'Sốt salat bánh mỳ ngọt',                         'Nguyên liệu', 'Kg',     75000),
  ('NL0041',          'Sốt ướp xá xíu',                                  'Nguyên liệu', 'Lọ',     65000),
  ('NL0069',          'Sữa bột',                                           'Nguyên liệu', 'Bao',    0),
  ('NL-SCA',          'Sữa chua ăn',                                       'Nguyên liệu', 'Hộp',    6700),
  ('NL-SDNSPN',       'Sữa đặc ngôi sao phương nam',                     'Nguyên liệu', 'Hộp',    73950),
  ('NL0002',          'Sữa tươi H-milk tiệt trùng nguyên kem 3.5% (12h/thùng)','Nguyên liệu','Hộp',24500),
  ('NL-SUATUOI-KHS',  'Sữa tươi faciate (thùng 12H)',                   'Nguyên liệu', 'Thùng',  335000),
  ('NL0289',          'Sunup ổi',                                          'Nguyên liệu', 'Chai',   0),
  ('NL0264',          'Sunup vải',                                         'Nguyên liệu', 'Chai',   0),
  ('NL0139',          'Táo đỏ',                                            'Nguyên liệu', 'Kg',     0),
  ('NL0280',          'Táo đỏ 1,2kg',                                     'Nguyên liệu', 'Kg',     0),
  ('NL0038',          'Thạch dừa thô loại 1kg/túi',                      'Nguyên liệu', 'Túi',    79000),
  ('NL0205',          'Thạch nổ củ năng',                                 'Nguyên liệu', 'Lon',    63000),
  ('NL0201',          'Thốt nốt rim',                                      'Nguyên liệu', 'Túi',    140000),
  ('NL0050',          'Tinh bột khoai tây (400g)',                        'Nguyên liệu', 'Túi',    0),
  ('NL0163',          'Tinh bột sắn 25kg',                               'Nguyên liệu', 'Bao',    1300000),
  ('NL0169',          'Tinh chất lá dứa 6 lọ/lốc',                      'Nguyên liệu', 'Lốc',    0),
  ('NL0221',          'Tỏi bóc sẵn',                                      'Nguyên liệu', 'Kg',     0),
  ('NL0011',          'Top pop Bơ BOS lỏng 18kg HN',                     'Nguyên liệu', 'Can',    1080000),
  ('NL0266',          'Trà ô long xanh queen',                            'Nguyên liệu', 'Gói',    0),
  ('NL0256',          'Trà Olong nhài việt tuấn',                        'Nguyên liệu', 'Túi',    168000),
  ('NL0253',          'Trà thái xanh',                                     'Nguyên liệu', 'Túi',    68000),
  ('NL0257',          'Trà xanh nhài việt tuấn',                         'Nguyên liệu', 'Túi',    143000),
  ('NL0105',          'Trân châu đen 3q',                                 'Nguyên liệu', 'Túi',    0),
  ('NL0219',          'Trân châu hoàng kim',                              'Nguyên liệu', 'Túi',    43000),
  ('NL0202',          'Trân châu sợi Toco',                               'Nguyên liệu', 'Gói',    45000),
  ('NL0209',          'Trân châu trắng 3Q',                               'Nguyên liệu', 'Túi',    58000),
  ('NL0276',          'Trứng cút',                                         'Nguyên liệu', 'Quả',    600),
  ('NL0107',          'Trứng muối 30q/khay',                              'Nguyên liệu', 'Khay',   195000),
  ('NL0236',          'Trứng muối vụn',                                   'Nguyên liệu', 'Túi',    0),
  ('NL0080',          'Trứng muối (100q/túi)',                            'Nguyên liệu', 'Túi',    370000),
  ('NL0119',          'Tương cà (can 2L)',                                'Nguyên liệu', 'Can',    60000),
  ('NL0187',          'Ức gà',                                             'Nguyên liệu', 'Kg',     0),
  ('NL0157',          'Việt quất tươi (12h/khay)',                        'Nguyên liệu', 'Khay',   299000),
  ('NL0091',          'Vụn dừa sấy',                                       'Nguyên liệu', 'Túi',    0),
  ('NL0165',          'Vừng lạc',                                          'Nguyên liệu', 'Lọ',     45000),
  ('NL0031',          'Vừng trắng',                                        'Nguyên liệu', 'Kg',     0),
  ('NL0034',          'Xả khô',                                            'Nguyên liệu', 'Kg',     0),
  ('NL0275',          'Xà lách',                                           'Nguyên liệu', 'Kg',     0),
  ('NL0228',          'Xả tươi',                                           'Nguyên liệu', 'Kg',     0),
  ('NL0297',          'Xì dầu đặc biệt LEEKUMKEE (Can 2l)',              'Nguyên liệu', 'Can',    0),
  ('NL0206',          'Xoài cát chu',                                      'Nguyên liệu', 'Kg',     40000),
  ('NL0115',          'Xoài sấy dẻo',                                      'Nguyên liệu', 'Kg',     0),
  ('NL0255',          'Xôi lá nếp cốt dừa',                              'Nguyên liệu', 'Túi',    58000),
  ('NL0055',          'Hình socola bé trai gái',                          'Nguyên liệu', 'Hộp',    0),
  ('NL0053',          'Hình socola chúc mừng năm mới',                   'Nguyên liệu', 'Hộp',    0),
  ('NL0054',          'Hình socola gấu dâu',                              'Nguyên liệu', 'Hộp',    0),
  ('NL0052',          'Hình socola mừng thọ',                             'Nguyên liệu', 'Hộp',    0),
  ('NL0051',          'Hình socola ông bà',                               'Nguyên liệu', 'Hộp',    0),
  -- ── VẬT LIỆU ─────────────────────────────────────────────
  ('VL-BDDV5',        'Băng dính hàng dễ vỡ',                            'Vật liệu',    'Cuộn',   0),
  ('VL-BD5',          'Băng dính trong cuộn to',                          'Vật liệu',    'Cuộn',   0),
  ('VL-BD2',          'Băng dính trong nhỏ 2cm',                         'Vật liệu',    'Cuộn',   0),
  ('VL-BG8',          'Bát giấy nâu size 8 làm maccaron',               'Vật liệu',    'Cọc',    25000),
  ('VL-BG10',         'Bát giấy trắng size 10 làm bánh bao',            'Vật liệu',    'Cọc',    32960),
  ('VL0160',          'Bìa 35x45',                                        'Vật liệu',    'Cái',    8000),
  ('PK-BODAO-TANH',   'Bộ dao đĩa',                                       'Vật liệu',    'Cái',    3800),
  ('VL-BODCCBS5-SKY', 'Bộ dụng cụ cơ bản 5 set',                        'Vật liệu',    'Bộ',     91000),
  ('VL-BOHOKKAIDO-LN','Bơ hokkaido Vivo (10 kg/kiện)',                   'Vật liệu',    'Kiện',   950000),
  ('VL-BONAMKIEU-SKY','Bơ Nam Kiều',                                      'Vật liệu',    'Thùng',  0),
  ('PK-BUTBI',        'Bút bi',                                            'Vật liệu',    'Cái',    5000),
  ('PK-BUTDA',        'Bút lông đen bé',                                  'Vật liệu',    'Chiếc',  0),
  ('PK-BUTDADAU',     'Bút lông xanh',                                    'Vật liệu',    'Chiếc',  0),
  ('VL0206',          'Can nước rửa bát',                                  'Vật liệu',    'Can',    0),
  ('VL0123',          'Chai đựng thạch dừa PET 500ml cổ 42 (dây 95c)',  'Vật liệu',    'Dây',    247000),
  ('VL0121',          'Chai sữa chua uống (dây 240c)',                   'Vật liệu',    'Chai',   1840),
  ('VL0061',          'Cốc cupcake size to',                              'Vật liệu',    'Dây',    20000),
  ('VL0132',          'Cốc đựng set 4/6',                                 'Vật liệu',    'Cái',    2000),
  ('VL0055',          'Cốc giấy bạc',                                     'Vật liệu',    'Chiếc',  866),
  ('VL0058',          'Cốc giấy cupcake nhỏ',                            'Vật liệu',    'Chiếc',  392),
  ('VL0096',          'Cốc giấy hoa nắp đen',                            'Vật liệu',    'Chiếc',  0),
  ('VL0069',          'Cốc giấy nâu',                                     'Vật liệu',    'Chiếc',  2100),
  ('VL0057',          'Cốc giấy tròn bé',                                'Vật liệu',    'Chiếc',  600),
  ('VL0056',          'Cốc giấy vuông',                                   'Vật liệu',    'Chiếc',  1680),
  ('VL0161',          'Cồn 70 độ',                                        'Vật liệu',    'Chai',   0),
  ('VL0187',          'Dây kẽm vàng buộc nơ',                            'Vật liệu',    'Cuộn',   0),
  ('VL0183',          'Dây thừng',                                        'Vật liệu',    'Cuộn',   32000),
  ('VL0107',          'Đế chống tầng trắng size 12',                     'Vật liệu',    'Chiếc',  8000),
  ('VL0108',          'Đế chống tầng trắng size 16',                     'Vật liệu',    'Chiếc',  10000),
  ('VL0109',          'Đế chống tầng trắng size 20',                     'Vật liệu',    'Chiếc',  13000),
  ('VL0110',          'Đế chống tầng trong suốt size 16',               'Vật liệu',    'Chiếc',  8000),
  ('VL0213',          'Đế đựng bánh lạnh size 9x9',                     'Vật liệu',    'Cái',    1250),
  ('VL0011',          'Đế ép chữ nhật 30x40cm',                         'Vật liệu',    'Cái',    3900),
  ('VL0007',          'Đế ngọc 24cm',                                     'Vật liệu',    'Cái',    1800),
  ('VL0008',          'Đế ngọc 26cm',                                     'Vật liệu',    'Cái',    2000),
  ('VL0009',          'Đế ngọc 30cm',                                     'Vật liệu',    'Cái',    2400),
  ('VL0010',          'Đế ngọc 32cm',                                     'Vật liệu',    'Cái',    2700),
  ('VL0128',          'Đế trắng size 30',                                 'Vật liệu',    'Cái',    2400),
  ('VL0159',          'Đế tròn size 20',                                  'Vật liệu',    'Cái',    0),
  ('VL0158',          'Đế tròn size 26',                                  'Vật liệu',    'Cái',    0),
  ('VL0157',          'Đế tròn size 28',                                  'Vật liệu',    'Cái',    0),
  ('VL0156',          'Đế tròn size 35',                                  'Vật liệu',    'Cái',    0),
  ('VL0034',          'Dĩa lẻ',                                           'Vật liệu',    'Túi',    80000),
  ('VL0033',          'Đĩa lẻ',                                           'Vật liệu',    'Túi',    28000),
  ('VL0143',          'Găng tay nilong hộp',                             'Vật liệu',    'Hộp',    15000),
  ('VL0153',          'Găng tay nilong túi',                             'Vật liệu',    'Túi',    0),
  ('VL0178',          'Ghim',                                             'Vật liệu',    'Hộp',    0),
  ('VL0165',          'Giấy ăn to thùng 36g',                           'Vật liệu',    'Gói',    15000),
  ('VL0120',          'Giấy ăn nhỏ thùng 20g',                          'Vật liệu',    'Gói',    9000),
  ('VL0006',          'Giấy decal nhiệt 100x75',                        'Vật liệu',    'Cuộn',   0),
  ('VL0204',          'Giấy gạo',                                        'Vật liệu',    'Tệp',    0),
  ('VL0004',          'Giấy in date cookie',                             'Vật liệu',    'Cuộn',   0),
  ('VL0005',          'Giấy in date trà cam quế',                       'Vật liệu',    'Cuộn',   0),
  ('VL0001',          'Giấy in hóa đơn',                                'Vật liệu',    'Cuộn',   6900),
  ('VL0012',          'Giấy lót khuôn',                                  'Vật liệu',    'Tập',    195000),
  ('VL0145',          'Giấy vệ sinh (bịch 10 cuộn)',                    'Vật liệu',    'Bịch',   110000),
  ('VL0221',          'Gum nặn bánh 600g',                              'Vật liệu',    'Túi',    115000),
  ('VL0049',          'Hộp 55C',                                         'Vật liệu',    'Chiếc',  530),
  ('VL0072',          'Hộp 6 ô đựng set 6 bánh trung thu',             'Vật liệu',    'Chiếc',  1850),
  ('VL0098',          'Hộp bánh trung thu đế đen nắp trong',           'Vật liệu',    'Chiếc',  1900),
  ('VL0065',          'Hộp bông lan ruốc ĐL',                           'Vật liệu',    'Dây',    37500),
  ('VL0063',          'Hộp cá trung thu',                               'Vật liệu',    'Chiếc',  0),
  ('VL0079',          'Hộp caramen nhỏ',                                'Vật liệu',    'Chiếc',  450),
  ('VL0090',          'Hộp caramen to',                                  'Vật liệu',    'Chiếc',  1120),
  ('VL0025',          'Hộp chuối (dây 100c)',                           'Vật liệu',    'Dây',    150000),
  ('VL0179',          'Hộp crep trà xanh scl (DÂY 50C)',               'Vật liệu',    'Dây',    0),
  ('VL0219',          'Hộp cửa sổ w1600 giấy crap',                    'Vật liệu',    'Cái',    4200),
  ('VL0218',          'Hộp cửa sổ w700 giấy crap',                     'Vật liệu',    'Cái',    2600),
  ('VL0142',          'Hộp đế nâu đựng RBB',                           'Vật liệu',    'Cái',    0),
  ('VL0045',          'Hộp đựng bánh bao 4c DP-53 (dây 50c)',          'Vật liệu',    'Chiếc',  1150),
  ('VL0103',          'Hộp đựng bánh bao nướng Quảng Đông (dây 50c)', 'Vật liệu',    'Dây',    169000),
  ('VL0104',          'Hộp đựng bánh bò to (dây 50)',                  'Vật liệu',    'Dây',    90000),
  ('VL0102',          'Hộp đựng bánh cuộn (dây 50c)',                  'Vật liệu',    'Chiếc',  42500),
  ('VL0082',          'Hộp đựng bánh dẻo nhỏ',                         'Vật liệu',    'Chiếc',  8000),
  ('VL0081',          'Hộp đựng bánh dẻo to',                          'Vật liệu',    'Chiếc',  10000),
  ('VL0105',          'Hộp đựng bánh mì/bánh bao',                     'Vật liệu',    'Chiếc',  0),
  ('VL0147',          'Hộp đựng bánh thỏi vàng (dây 50c)',             'Vật liệu',    'Chiếc',  160000),
  ('VL0043',          'Hộp đựng bánh trung thu set 6 vị',              'Vật liệu',    'Chiếc',  0),
  ('H-XY581',         'Hộp đựng cupcake hq/kem mặn',                   'Vật liệu',    'Chiếc',  1500),
  ('VL0037',          'Hộp đựng Cupcake vani H17 (dây 100c)',          'Vật liệu',    'Cái',    50000),
  ('VL0046',          'Hộp đựng gato cắt C55 (dây 100c)',              'Vật liệu',    'Dây',    50000),
  ('VL0076',          'Hộp đựng maccaron đế nâu',                      'Vật liệu',    'Chiếc',  2000),
  ('VL0073',          'Hộp đựng mochi 4 viên đế đen',                  'Vật liệu',    'Chiếc',  3300),
  ('VL0091',          'Hộp đựng nước canh',                            'Vật liệu',    'Chiếc',  600),
  ('VL0074',          'Hộp đựng ốc kem',                               'Vật liệu',    'Dây',    100000),
  ('VL0083',          'Hộp đựng set hoa quả sấy dẻo JLH999',          'Vật liệu',    'Chiếc',  7500),
  ('VL0047',          'Hộp đựng su kem H50 (dây 100c)',                'Vật liệu',    'Chiếc',  25000),
  ('VL0077',          'Hộp đựng trứng cake chuối (dây50c)',            'Vật liệu',    'Dây',    150000),
  ('VL0112',          'Hộp gato 24 (50c)',                              'Vật liệu',    'Hộp',    0),
  ('VL0111',          'Hộp gato 26 (60c)',                              'Vật liệu',    'Hộp',    9000),
  ('VL0113',          'Hộp gato 30 (30c)',                              'Vật liệu',    'Hộp',    10000),
  ('VL0116',          'Hộp gato 30x40',                                 'Vật liệu',    'Hộp',    0),
  ('VL0114',          'Hộp gato 32',                                    'Vật liệu',    'Hộp',    13000),
  ('VL0115',          'Hộp gato 35x45',                                 'Vật liệu',    'Hộp',    15000),
  ('VL0144',          'Hộp gato cắt giấy',                             'Vật liệu',    'Hộp',    1700),
  ('VL0067',          'Hộp gato mini (dây 100c)',                      'Vật liệu',    'Dây',    125000),
  ('VL0118',          'Hộp gato nắp rời size 30',                      'Vật liệu',    'Hộp',    0),
  ('VL0101',          'Hộp giấy đựng bánh mỳ bơ đường',               'Vật liệu',    'Chiếc',  5000),
  ('VL0080',          'Hộp giấy đựng da lợn đế trắng',                'Vật liệu',    'Chiếc',  0),
  ('VL0078',          'Hộp giấy đựng vỏ ốc quế',                      'Vật liệu',    'Chiếc',  800),
  ('VL0087',          'Hộp giấy nâu 2 ngăn nắp trong',                'Vật liệu',    'Chiếc',  3920),
  ('VL0048',          'Hộp H23',                                        'Vật liệu',    'Chiếc',  421),
  ('VL0026',          'Hộp HT12 (dây 100c)',                           'Vật liệu',    'Dây',    60000),
  ('VL0203',          'Hộp mica 40x60',                                 'Vật liệu',    'Cái',    105000),
  ('VL0151',          'Hộp mica size 22',                              'Vật liệu',    'Bộ',     16000),
  ('VL0182',          'Hộp mica size 40',                              'Vật liệu',    'Chiếc',  0),
  ('VL0044',          'Hộp mouse cốc lẻ',                              'Vật liệu',    'Chiếc',  2500),
  ('VL0095',          'Hộp nhựa chữ nhật 1000ml',                     'Vật liệu',    'Chiếc',  2725),
  ('VL0094',          'Hộp nhựa chữ nhật 550ml',                      'Vật liệu',    'Chiếc',  3000),
  ('VL0092',          'Hộp nhựa chữ nhật 750ml',                      'Vật liệu',    'Chiếc',  2900),
  ('VL0106',          'Hộp nhựa đáy 4 ngăn đựng cơm',                'Vật liệu',    'Chiếc',  2250),
  ('VL0217',          'Hộp nhựa fk333 bao nướng/bơ tỏi 50c/túi',     'Vật liệu',    'Túi',    2000),
  ('VL0100',          'Hộp nhựa HX561',                               'Vật liệu',    'Chiếc',  0),
  ('VL0093',          'Hộp nhựa tròn cao 700ml',                      'Vật liệu',    'Chiếc',  11600),
  ('VL0086',          'Hộp oval red/choco/bltm (dây 50c)',            'Vật liệu',    'Dây',    90000),
  ('VL0208',          'Hộp pizza size 19',                             'Vật liệu',    'Cái',    1450),
  ('VL0209',          'Hộp pizza size 31',                             'Vật liệu',    'Cái',    2700),
  ('VL0223',          'Hộp quây tròn gato 2 tầng',                    'Vật liệu',    'Chiếc',  0),
  ('VL0027',          'Hộp Sandwich vuông gấu vàng (dây 50c)',        'Vật liệu',    'Dây',    72500),
  ('VL0066',          'Hộp tam giác đế đen',                          'Vật liệu',    'Chiếc',  1600),
  ('VL0181',          'Hộp tart trứng (DÂY 50C)',                     'Vật liệu',    'Chiếc',  0),
  ('VL0070',          'Hộp thiếc chữ nhật không nắp',                'Vật liệu',    'Chiếc',  6000),
  ('VL0068',          'Hộp thiếc vuông nắp trong',                   'Vật liệu',    'Chiếc',  9100),
  ('VL0088',          'Hộp tiramisu tròn',                            'Vật liệu',    'Chiếc',  3000),
  ('VL0186',          'Hộp tiramisu vuông',                           'Vật liệu',    'Chiếc',  0),
  ('VL0119',          'Hộp trà cam quế giấy detox',                  'Vật liệu',    'Hộp',    0),
  ('VL0099',          'Hộp tròn đế giấy nắp trong',                  'Vật liệu',    'Chiếc',  0),
  ('VL0211',          'Hộp tròn nhựa 600ml',                         'Vật liệu',    'Cái',    1800),
  ('VL0089',          'Hộp vuông BLTM',                               'Vật liệu',    'Chiếc',  3000),
  ('VL0085',          'Hộp vuông to trong suốt W01',                 'Vật liệu',    'Chiếc',  7200),
  ('VL0084',          'Hộp vuông trong suốt JLH10-6',                'Vật liệu',    'Chiếc',  2500),
  ('VL0216',          'Hũ đựng sốt liền nắp 2,5oz (50c/lốc)',       'Vật liệu',    'Lốc',    23000),
  ('VL0215',          'Hũ đựng sốt liền nắp 2oz (50c/lốc)',         'Vật liệu',    'Lốc',    16000),
  ('VL0152',          'Hũ sữa chua nhựa',                            'Vật liệu',    'Cái',    0),
  ('VL0222',          'Kéo',                                          'Vật liệu',    'Chiếc',  0),
  ('VL0162',          'Khăn lau',                                     'Vật liệu',    'Cái',    0),
  ('VL0210',          'Khay nhựa',                                    'Vật liệu',    'Cái',    279783),
  ('VL0071',          'Khay thiếc tròn nhỏ',                         'Vật liệu',    'Chiếc',  1000),
  ('VL0149',          'Lọ 1000ml (72c/kiện)',                        'Vật liệu',    'Cái',    0),
  ('VL0133',          'Lọ dẹt 330ml',                                'Vật liệu',    'Cái',    0),
  ('VL0134',          'Lọ dẹt 500ml',                                'Vật liệu',    'Cái',    0),
  ('VL0126',          'Lọ tròn 1500ml (66c/kiện)',                   'Vật liệu',    'Cái',    6800),
  ('VL0127',          'Lọ tròn 500ml (98c/kiện)',                    'Vật liệu',    'Cái',    4600),
  ('VL0125',          'Lọ tròn 750ml (131c/thùng)',                  'Vật liệu',    'Cái',    4600),
  ('VL0205',          'Lon 500ml (171c/kiện)',                        'Vật liệu',    'Kiện',   3335),
  ('VL0220',          'Lon chè 330 (thùng 258)',                     'Vật liệu',    'Cái',    2875),
  ('VL0131',          'Lon trà sữa 330ml (dây 83c)',                 'Vật liệu',    'Cái',    2875),
  ('VL0148',          'Màng bọc thực phẩm',                          'Vật liệu',    'Hộp',    75000),
  ('VL0039',          'Nắp hộp gato red/choco',                      'Vật liệu',    'Cái',    0),
  ('VL0172',          'Nến chữ HPBĐ',                                'Vật liệu',    'Bộ',     0),
  ('VL0038',          'Nến số vàng',                                  'Vật liệu',    'Cái',    1450),
  ('VL0141',          'Nến tăm lẻ',                                   'Vật liệu',    'Vỉ',     1200),
  ('VL0194',          'Nến xoắn',                                     'Vật liệu',    'Hộp',    4000),
  ('VL0170',          'Nhện nhựa PK',                                 'Vật liệu',    'Túi',    0),
  ('VL0192',          'Nhiệt kế keo tròn',                           'Vật liệu',    'Cái',    30000),
  ('VL0196',          'Nơ trắng + hồng',                             'Vật liệu',    'Cái',    12000),
  ('VL0146',          'Nước rửa bát',                                 'Vật liệu',    'Túi',    16000),
  ('VL0021',          'Oto suvs PK',                                  'Vật liệu',    'Cái',    3500),
  ('VL0036',          'Pháo phụt',                                    'Vật liệu',    'Túi',    13000),
  ('VL0154',          'Quây trong size 10',                          'Vật liệu',    'Cuộn',   68000),
  ('VL0155',          'Quây trong size 12',                          'Vật liệu',    'Cuộn',   75000),
  ('VL0180',          'Quây trong size 8',                           'Vật liệu',    'Cuộn',   68000),
  ('VL-HOP4N',        'Set 4 (hộp 4 chi tiết)',                     'Vật liệu',    'Bộ',     10000),
  ('VL-HOP6N',        'Set 6 (hộp 4 chi tiết)',                     'Vật liệu',    'Bộ',     12000),
  ('VL0117',          'Thìa ăn chè 100c/túi',                       'Vật liệu',    'Túi',    20000),
  ('VL0175',          'Thìa đĩa thêm (10c)',                        'Vật liệu',    'Bộ',     0),
  ('VL0174',          'Thìa đĩa thêm (5c)',                         'Vật liệu',    'Bộ',     0),
  ('VL0024',          'Thìa nhựa (2kg)',                             'Vật liệu',    'Túi',    70000),
  ('VL0184',          'Túi bánh mỳ gối 50c/tập',                   'Vật liệu',    'Tập',    0),
  ('VL0129',          'Túi chéo bắt kem loại to (100c tập)',        'Vật liệu',    'Tập',    65000),
  ('VL0042',          'Túi đỏ happy everyday',                      'Vật liệu',    'Chiếc',  14500),
  ('VL0041',          'Túi đỏ happy time',                          'Vật liệu',    'Chiếc',  13600),
  ('VL0191',          'Túi đóng chè sỉ 1kg',                       'Vật liệu',    'Kg',     140000),
  ('VL0051',          'Túi đựng bánh trung thu nâu',               'Vật liệu',    'Chiếc',  11000),
  ('VL0050',          'Túi đựng cookie 500g',                       'Vật liệu',    'Chiếc',  1320),
  ('VL0173',          'Túi gato sấy',                               'Vật liệu',    'Cái',    0),
  ('VL0214',          'Túi giữ nhiệt chum chum',                    'Vật liệu',    'Cái',    4000),
  ('VL0054',          'Túi hoa đựng set 4',                         'Vật liệu',    'Chiếc',  12000),
  ('VL0053',          'Túi hoa đựng set 6',                         'Vật liệu',    'Chiếc',  15000),
  ('VL0124',          'Túi hút chân không',                         'Vật liệu',    'Cái',    0),
  ('VL0212',          'Túi hút chân không pizza',                   'Vật liệu',    'Kg',     70000),
  ('VL0150',          'Túi nilong đỏ',                              'Vật liệu',    'Kg',     45000),
  ('VL0140',          'Túi nilong rác đen',                         'Vật liệu',    'Kg',     35000),
  ('VL0139',          'Túi nilong trắng bé',                        'Vật liệu',    'Tập',    45000),
  ('VL0138',          'Túi nilong trắng nhỡ',                       'Vật liệu',    'Tập',    45000),
  ('VL0136',          'Túi nilong trắng to',                        'Vật liệu',    'Tập',    45000),
  ('VL0135',          'Túi nilong vàng',                            'Vật liệu',    'Tập',    45000),
  ('VL0137',          'Túi nilong xanh',                            'Vật liệu',    'Tập',    45000),
  ('VL0052',          'Túi trắng giấy',                             'Vật liệu',    'Chiếc',  4653),
  ('VL0130',          'Túi trắng to đựng mứt dừa',                 'Vật liệu',    'Cái',    0),
  ('VL0190',          'Túi zip bizonzon',                           'Vật liệu',    'Chiếc',  0),
  ('VL0207',          'Túi zip trắng size to (22x28x10)',           'Vật liệu',    'Cái',    2500),
  ('VL0028',          'Vỏ mochi 2 cái X202 (dây 100c)',            'Vật liệu',    'Cái',    1400),
  ('VL0188',          'Bóng nhũ vàng/bạc/xanh dương',              'Vật liệu',    'Túi',    23000),
  ('VL0013',          'Thẻ cắm hoạt hình',                         'Vật liệu',    'Set',    3000),
  ('VL0015',          'Thẻ meka happy birthday (túi 10c)',         'Vật liệu',    'Túi',    12000),
  ('VL0202',          'Topper 8/3 PK',                              'Vật liệu',    'Set',    16000),
  ('VL0017',          'Set bi nhựa 4 cỡ',                          'Vật liệu',    'Túi',    24500),
  ('VL0201',          'Set giấy 8/3 PK',                           'Vật liệu',    'Set',    3000),
  ('VL0040',          'Set khay kẹo nougat',                        'Vật liệu',    'Set',    420000),
  ('VL0199',          'Set phi hành gia PK',                        'Vật liệu',    'Set',    28000),
  ('VL0016',          'Set tai thỏ',                                'Vật liệu',    'Túi',    4000),
  ('VL0020',          'Siêu nhân nhựa (7 con) PK',                 'Vật liệu',    'Túi',    10000),
  ('VL0167',          'Ông bà cụ nhựa PK',                         'Vật liệu',    'Chiếc',  3500),
  ('VL0198',          'Khủng long to PK',                           'Vật liệu',    'Cái',    9000),
  ('VL0023',          'Khung thành cầu thủ PK',                    'Vật liệu',    'Túi',    14500),
  ('VL0169',          'Kurumi nhựa PK',                             'Vật liệu',    'Chiếc',  5000),
  ('VL0197',          'Ruy băng 2cm PK',                           'Vật liệu',    'Cây',    70000),
  ('VL0200',          'Ruy von PK',                                 'Vật liệu',    'Cuộn',   8000),
  ('VL0019',          'Kẹo bi trắng ngọc trai mix size gói 500g', 'Vật liệu',    'Gói',    82000),
  ('VL0035',          'Kẹo đồng tiền PK',                          'Vật liệu',    'Kg',     90000),
  ('VL0022',          'Mèo kity đơn PK',                           'Vật liệu',    'Con',    2500),
  ('VL0014',          'Cành đào màu đỏ màu vàng',                  'Vật liệu',    'Cái',    5500),
  ('VL0168',          'Cây dừa PK',                                 'Vật liệu',    'Bộ',     0),
  ('VL0171',          'Bi vàng nhựa PK',                           'Vật liệu',    'Túi',    0),
  ('VL0195',          'Elsa PK',                                    'Vật liệu',    'Cái',    7000),
  ('VL0018',          'Em bé múa bale tóc hồng cánh nhỏ',          'Vật liệu',    'Con',    6000),
  ('VL0032',          'Quây hoa',                                   'Vật liệu',    'Cái',    5000)
) AS v(code, name, category, unit, cost_price), u
ON CONFLICT (code) DO UPDATE SET
  name       = EXCLUDED.name,
  category   = EXCLUDED.category,
  unit       = EXCLUDED.unit,
  cost_price = EXCLUDED.cost_price;

COMMIT;

-- Kiểm tra kết quả
SELECT category, COUNT(*) as so_luong FROM products GROUP BY category ORDER BY category;
